/*
Copyright (c) 2018 Intrepid Control Systems, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _NRF52832_S132_MEMMAP_H
#define _NRF52832_S132_MEMMAP_H

#include "nrf_mbr.h"
#include "nrf_sdm.h"

// nRF52832 MBR Section 4KB
#define MBR_START (0)
#define MBR_END (0x1000)
#define MBR_MAX_SIZE (MBR_END - MBR_START)

#if (SD_MAJOR_VERSION == 5)
// nRF52832 Bootloader Settings 4KB
#define BOOTLOADER_SETTINGS_START	(0x7F000)
#define BOOTLOADER_SETTINGS_END		(0x80000)
#define BOOTLOADER_SETTINGS_MAX_SIZE	(BOOTLOADER_SETTINGS_END - BOOTLOADER_SETTINGS_START)

// nRF52832 Bootloader MBR Parameter Storage 4KB
#define BOOTLOADER_MBRPARAM_START	(0x7E000)
#define BOOTLOADER_MBRPARAM_END		(0x7F000)
#define BOOTLOADER_MBRPARAM_MAX_SIZE	(BOOTLOADER_MBRPARAM_END - BOOTLOADER_MBRPARAM_START)

// nRF52832 Bootloader Region including MBR Param 28KB
#define BOOTLOADER_REGION_START		(0x78000)
#define BOOTLOADER_REGION_END		(0x7F000)
#define BOOTLOADER_MAX_SIZE			(BOOTLOADER_REGION_END - BOOTLOADER_REGION_START)

// nRF52832 Application Area 352KB
#define APPLICATION_ADDRESS_START   (0x20000)
#define APPLICATION_ADDRESS_END		(0x78000)
#define APPLICATION_MAX_SIZE		(APPLICATION_ADDRESS_END - APPLICATION_ADDRESS_START)

// nRF52832 Softdevice Area 124KB
#define SD_ADDRESS_START			(0x1000)
#define SD_ADDRESS_END				(0x20000)
#define SD_MAX_SIZE					(SD_ADDRESS_END - SD_ADDRESS_START)

// nRF52832 FLASH 512KB / 4KB Pages / 512B Blocks
#define NRF52832_FLASHSIZE			(512 * 1024)
#define NRF52832_PAGESIZE			(4096)
#define NRF52832_BLOCKSIZE			(512)
#define FIRMWARE_LAST_BLOCK_INDEX	(959 * 512) // 4096 byte sectors, 960 is bootloader
#elif (SD_MAJOR_VERSION == 4)
// nRF52832 Bootloader Settings 4KB
#define BOOTLOADER_SETTINGS_START	(0x7F000)
#define BOOTLOADER_SETTINGS_END		(0x80000)
#define BOOTLOADER_SETTINGS_MAX_SIZE	(BOOTLOADER_SETTINGS_END - BOOTLOADER_SETTINGS_START)

// nRF52832 Bootloader MBR Parameter Storage 4KB
#define BOOTLOADER_MBRPARAM_START	(0x7E000)
#define BOOTLOADER_MBRPARAM_END		(0x7F000)
#define BOOTLOADER_MBRPARAM_MAX_SIZE	(BOOTLOADER_MBRPARAM_END - BOOTLOADER_MBRPARAM_START)

// nRF52832 Bootloader Region including MBR Param 28KB
#define BOOTLOADER_REGION_START		(0x78000)
#define BOOTLOADER_REGION_END		(0x7F000)
#define BOOTLOADER_MAX_SIZE			(BOOTLOADER_REGION_END - BOOTLOADER_REGION_START)

// nRF52832 Application Area 356KB
#define APPLICATION_ADDRESS_START   (0x1F000)
#define APPLICATION_ADDRESS_END		(0x78000)
#define APPLICATION_MAX_SIZE		(APPLICATION_ADDRESS_END - APPLICATION_ADDRESS_START)

// nRF52832 Softdevice Area 120KB
#define SD_ADDRESS_START			(0x1000)
#define SD_ADDRESS_END				(0x1F000)
#define SD_MAX_SIZE					(SD_ADDRESS_END - SD_ADDRESS_START)

// nRF52832 FLASH 512KB / 4KB Pages / 512B Blocks
#define NRF52832_FLASHSIZE			(512 * 1024)
#define NRF52832_PAGESIZE			(4096)
#define NRF52832_BLOCKSIZE			(512)
#define FIRMWARE_LAST_BLOCK_INDEX	(959 * 512) // 4096 byte sectors, 960 is bootloader
#elif (SD_MAJOR_VERSION == 3)
// nRF52832 Bootloader Settings 4KB
#define BOOTLOADER_SETTINGS_START	(0x7F000)
#define BOOTLOADER_SETTINGS_END		(0x80000)
#define BOOTLOADER_SETTINGS_MAX_SIZE	(BOOTLOADER_SETTINGS_END - BOOTLOADER_SETTINGS_START)

// nRF52832 Bootloader MBR Parameter Storage 4KB
#define BOOTLOADER_MBRPARAM_START	(0x7E000)
#define BOOTLOADER_MBRPARAM_END		(0x7F000)
#define BOOTLOADER_MBRPARAM_MAX_SIZE	(BOOTLOADER_MBRPARAM_END - BOOTLOADER_MBRPARAM_START)

// nRF52832 Bootloader Region including MBR Param 28KB
#define BOOTLOADER_REGION_START		(0x78000)
#define BOOTLOADER_REGION_END		(0x7F000)
#define BOOTLOADER_MAX_SIZE			(BOOTLOADER_REGION_END - BOOTLOADER_REGION_START)

// nRF52832 Application Area 356KB
#define APPLICATION_ADDRESS_START   (0x1F000)
#define APPLICATION_ADDRESS_END		(0x78000)
#define APPLICATION_MAX_SIZE		(APPLICATION_ADDRESS_END - APPLICATION_ADDRESS_START)

// nRF52832 Softdevice Area 120KB
#define SD_ADDRESS_START			(0x1000)
#define SD_ADDRESS_END				(0x1F000)
#define SD_MAX_SIZE					(SD_ADDRESS_END - SD_ADDRESS_START)

// nRF52832 FLASH 512KB / 4KB Pages / 512B Blocks
#define NRF52832_FLASHSIZE			(512 * 1024)
#define NRF52832_PAGESIZE			(4096)
#define NRF52832_BLOCKSIZE			(512)
#define FIRMWARE_LAST_BLOCK_INDEX	(959 * 512) // 4096 byte sectors, 960 is bootloader
#else
#error "Soft Device Version Not Supported for This Bootloader!"
#endif

#endif // _NRF52832_S132_MEMMAP_H
